#ifndef NACCESSIBLECONFIG_P_H
#define NACCESSIBLECONFIG_P_H

#include <QtGlobal>

#if QT_VERSION >= QT_VERSION_CHECK(6, 5, 0)
#define QTNATIVEUI_HAS_ACCESSIBLE_SELECTION_INTERFACE 1
#else
#define QTNATIVEUI_HAS_ACCESSIBLE_SELECTION_INTERFACE 0
#endif

#endif
