// WARNING: This file is automatically generated.
// DO NOT EDIT IT MANUALLY!
//
// Generated from Microsoft's Fluent UI XAML Theme Resources
// Source: https://github.com/microsoft/microsoft-ui-xaml
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#ifndef NFLUENTCOLORS_H
#define NFLUENTCOLORS_H

#include <QColor>
#include <QString>
#include <QMap>
#include <QMetaEnum>

// 辅助函数：创建带有alpha值的颜色（alpha为0-255）
inline QColor colorWithAlpha(int r, int g, int b, int alpha) {
    return QColor(r, g, b, alpha);
}

// 辅助函数：从现有颜色创建带有alpha值的颜色
inline QColor colorWithAlpha(const QColor& baseColor, int alpha) {
    QColor color = baseColor;
    color.setAlpha(alpha);
    return color;
}

// 辅助函数：创建带有百分比alpha值的颜色（alphaPercent为0-100）
inline QColor colorWithAlphaPercent(int r, int g, int b, int alphaPercent) {
    int alpha = static_cast<int>(255.0 * alphaPercent / 100.0);
    return QColor(r, g, b, alpha);
}

// 辅助函数：从现有颜色创建带有百分比alpha值的颜色
inline QColor colorWithAlphaPercent(const QColor& baseColor, int alphaPercent) {
    QColor color = baseColor;
    int alpha = static_cast<int>(255.0 * alphaPercent / 100.0);
    color.setAlpha(alpha);
    return color;
}

// Fluent Design 颜色枚举 - 自动生成
namespace NFluentColorKey {
    enum Key {
        AccentFillColorDisabled,
        AccentTextFillColorDisabled,
        CardBackgroundFillColorDefault,
        CardBackgroundFillColorSecondary,
        CardStrokeColorDefault,
        CardStrokeColorDefaultSolid,
        ControlAltFillColorDisabled,
        ControlAltFillColorQuarternary,
        ControlAltFillColorSecondary,
        ControlAltFillColorTertiary,
        ControlAltFillColorTransparent,
        ControlBaseLine,
        ControlFillColorDefault,
        ControlFillColorDisabled,
        ControlFillColorInputActive,
        ControlFillColorSecondary,
        ControlFillColorTertiary,
        ControlFillColorTransparent,
        ControlOnImageFillColorDefault,
        ControlOnImageFillColorDisabled,
        ControlOnImageFillColorSecondary,
        ControlOnImageFillColorTertiary,
        ControlSolidFillColorDefault,
        ControlStrokeColorDefault,
        ControlStrokeColorForStrongFillWhenOnImage,
        ControlStrokeColorOnAccentDefault,
        ControlStrokeColorOnAccentDisabled,
        ControlStrokeColorOnAccentSecondary,
        ControlStrokeColorOnAccentTertiary,
        ControlStrokeColorSecondary,
        ControlStrongFillColorDefault,
        ControlStrongFillColorDisabled,
        ControlStrongStrokeColorDefault,
        ControlStrongStrokeColorDisabled,
        DividerStrokeColorDefault,
        FocusStrokeColorInner,
        FocusStrokeColorOuter,
        LayerFillColorAlt,
        LayerFillColorDefault,
        LayerOnAccentAcrylicFillColorDefault,
        LayerOnAcrylicFillColorDefault,
        LayerOnMicaBaseAltFillColorDefault,
        LayerOnMicaBaseAltFillColorSecondary,
        LayerOnMicaBaseAltFillColorTertiary,
        LayerOnMicaBaseAltFillColorTransparent,
        SmokeFillColorDefault,
        SolidBackgroundFillColorBase,
        SolidBackgroundFillColorBaseAlt,
        SolidBackgroundFillColorQuarternary,
        SolidBackgroundFillColorSecondary,
        SolidBackgroundFillColorTertiary,
        SolidBackgroundFillColorTransparent,
        SubtleFillColorDisabled,
        SubtleFillColorSecondary,
        SubtleFillColorTertiary,
        SubtleFillColorTransparent,
        SurfaceStrokeColorDefault,
        SurfaceStrokeColorFlyout,
        SurfaceStrokeColorInverse,
        SystemColorButtonFaceColor,
        SystemColorButtonTextColor,
        SystemColorGrayTextColor,
        SystemColorHighlightColor,
        SystemColorHighlightTextColor,
        SystemColorHotlightColor,
        SystemColorWindowColor,
        SystemColorWindowTextColor,
        SystemFillColorAttentionBackground,
        SystemFillColorCaution,
        SystemFillColorCautionBackground,
        SystemFillColorCritical,
        SystemFillColorCriticalBackground,
        SystemFillColorNeutral,
        SystemFillColorNeutralBackground,
        SystemFillColorSolidAttentionBackground,
        SystemFillColorSolidNeutral,
        SystemFillColorSolidNeutralBackground,
        SystemFillColorSuccess,
        SystemFillColorSuccessBackground,
        TextFillColorDisabled,
        TextFillColorInverse,
        TextFillColorPrimary,
        TextFillColorSecondary,
        TextFillColorTertiary,
        TextOnAccentFillColorDisabled,
        TextOnAccentFillColorPrimary,
        TextOnAccentFillColorSecondary,
        TextOnAccentFillColorSelectedText,
        Count  // 用于计数和边界检查
    };
}

// 枚举到字符串的转换函数
inline QString fluentColorKeyToString(NFluentColorKey::Key key) {
    switch (key) {
        case NFluentColorKey::AccentFillColorDisabled:
            return "AccentFillColorDisabled";
        case NFluentColorKey::AccentTextFillColorDisabled:
            return "AccentTextFillColorDisabled";
        case NFluentColorKey::CardBackgroundFillColorDefault:
            return "CardBackgroundFillColorDefault";
        case NFluentColorKey::CardBackgroundFillColorSecondary:
            return "CardBackgroundFillColorSecondary";
        case NFluentColorKey::CardStrokeColorDefault:
            return "CardStrokeColorDefault";
        case NFluentColorKey::CardStrokeColorDefaultSolid:
            return "CardStrokeColorDefaultSolid";
        case NFluentColorKey::ControlAltFillColorDisabled:
            return "ControlAltFillColorDisabled";
        case NFluentColorKey::ControlAltFillColorQuarternary:
            return "ControlAltFillColorQuarternary";
        case NFluentColorKey::ControlAltFillColorSecondary:
            return "ControlAltFillColorSecondary";
        case NFluentColorKey::ControlAltFillColorTertiary:
            return "ControlAltFillColorTertiary";
        case NFluentColorKey::ControlAltFillColorTransparent:
            return "ControlAltFillColorTransparent";
        case NFluentColorKey::ControlBaseLine:
            return "ControlBaseLine";
        case NFluentColorKey::ControlFillColorDefault:
            return "ControlFillColorDefault";
        case NFluentColorKey::ControlFillColorDisabled:
            return "ControlFillColorDisabled";
        case NFluentColorKey::ControlFillColorInputActive:
            return "ControlFillColorInputActive";
        case NFluentColorKey::ControlFillColorSecondary:
            return "ControlFillColorSecondary";
        case NFluentColorKey::ControlFillColorTertiary:
            return "ControlFillColorTertiary";
        case NFluentColorKey::ControlFillColorTransparent:
            return "ControlFillColorTransparent";
        case NFluentColorKey::ControlOnImageFillColorDefault:
            return "ControlOnImageFillColorDefault";
        case NFluentColorKey::ControlOnImageFillColorDisabled:
            return "ControlOnImageFillColorDisabled";
        case NFluentColorKey::ControlOnImageFillColorSecondary:
            return "ControlOnImageFillColorSecondary";
        case NFluentColorKey::ControlOnImageFillColorTertiary:
            return "ControlOnImageFillColorTertiary";
        case NFluentColorKey::ControlSolidFillColorDefault:
            return "ControlSolidFillColorDefault";
        case NFluentColorKey::ControlStrokeColorDefault:
            return "ControlStrokeColorDefault";
        case NFluentColorKey::ControlStrokeColorForStrongFillWhenOnImage:
            return "ControlStrokeColorForStrongFillWhenOnImage";
        case NFluentColorKey::ControlStrokeColorOnAccentDefault:
            return "ControlStrokeColorOnAccentDefault";
        case NFluentColorKey::ControlStrokeColorOnAccentDisabled:
            return "ControlStrokeColorOnAccentDisabled";
        case NFluentColorKey::ControlStrokeColorOnAccentSecondary:
            return "ControlStrokeColorOnAccentSecondary";
        case NFluentColorKey::ControlStrokeColorOnAccentTertiary:
            return "ControlStrokeColorOnAccentTertiary";
        case NFluentColorKey::ControlStrokeColorSecondary:
            return "ControlStrokeColorSecondary";
        case NFluentColorKey::ControlStrongFillColorDefault:
            return "ControlStrongFillColorDefault";
        case NFluentColorKey::ControlStrongFillColorDisabled:
            return "ControlStrongFillColorDisabled";
        case NFluentColorKey::ControlStrongStrokeColorDefault:
            return "ControlStrongStrokeColorDefault";
        case NFluentColorKey::ControlStrongStrokeColorDisabled:
            return "ControlStrongStrokeColorDisabled";
        case NFluentColorKey::DividerStrokeColorDefault:
            return "DividerStrokeColorDefault";
        case NFluentColorKey::FocusStrokeColorInner:
            return "FocusStrokeColorInner";
        case NFluentColorKey::FocusStrokeColorOuter:
            return "FocusStrokeColorOuter";
        case NFluentColorKey::LayerFillColorAlt:
            return "LayerFillColorAlt";
        case NFluentColorKey::LayerFillColorDefault:
            return "LayerFillColorDefault";
        case NFluentColorKey::LayerOnAccentAcrylicFillColorDefault:
            return "LayerOnAccentAcrylicFillColorDefault";
        case NFluentColorKey::LayerOnAcrylicFillColorDefault:
            return "LayerOnAcrylicFillColorDefault";
        case NFluentColorKey::LayerOnMicaBaseAltFillColorDefault:
            return "LayerOnMicaBaseAltFillColorDefault";
        case NFluentColorKey::LayerOnMicaBaseAltFillColorSecondary:
            return "LayerOnMicaBaseAltFillColorSecondary";
        case NFluentColorKey::LayerOnMicaBaseAltFillColorTertiary:
            return "LayerOnMicaBaseAltFillColorTertiary";
        case NFluentColorKey::LayerOnMicaBaseAltFillColorTransparent:
            return "LayerOnMicaBaseAltFillColorTransparent";
        case NFluentColorKey::SmokeFillColorDefault:
            return "SmokeFillColorDefault";
        case NFluentColorKey::SolidBackgroundFillColorBase:
            return "SolidBackgroundFillColorBase";
        case NFluentColorKey::SolidBackgroundFillColorBaseAlt:
            return "SolidBackgroundFillColorBaseAlt";
        case NFluentColorKey::SolidBackgroundFillColorQuarternary:
            return "SolidBackgroundFillColorQuarternary";
        case NFluentColorKey::SolidBackgroundFillColorSecondary:
            return "SolidBackgroundFillColorSecondary";
        case NFluentColorKey::SolidBackgroundFillColorTertiary:
            return "SolidBackgroundFillColorTertiary";
        case NFluentColorKey::SolidBackgroundFillColorTransparent:
            return "SolidBackgroundFillColorTransparent";
        case NFluentColorKey::SubtleFillColorDisabled:
            return "SubtleFillColorDisabled";
        case NFluentColorKey::SubtleFillColorSecondary:
            return "SubtleFillColorSecondary";
        case NFluentColorKey::SubtleFillColorTertiary:
            return "SubtleFillColorTertiary";
        case NFluentColorKey::SubtleFillColorTransparent:
            return "SubtleFillColorTransparent";
        case NFluentColorKey::SurfaceStrokeColorDefault:
            return "SurfaceStrokeColorDefault";
        case NFluentColorKey::SurfaceStrokeColorFlyout:
            return "SurfaceStrokeColorFlyout";
        case NFluentColorKey::SurfaceStrokeColorInverse:
            return "SurfaceStrokeColorInverse";
        case NFluentColorKey::SystemColorButtonFaceColor:
            return "SystemColorButtonFaceColor";
        case NFluentColorKey::SystemColorButtonTextColor:
            return "SystemColorButtonTextColor";
        case NFluentColorKey::SystemColorGrayTextColor:
            return "SystemColorGrayTextColor";
        case NFluentColorKey::SystemColorHighlightColor:
            return "SystemColorHighlightColor";
        case NFluentColorKey::SystemColorHighlightTextColor:
            return "SystemColorHighlightTextColor";
        case NFluentColorKey::SystemColorHotlightColor:
            return "SystemColorHotlightColor";
        case NFluentColorKey::SystemColorWindowColor:
            return "SystemColorWindowColor";
        case NFluentColorKey::SystemColorWindowTextColor:
            return "SystemColorWindowTextColor";
        case NFluentColorKey::SystemFillColorAttentionBackground:
            return "SystemFillColorAttentionBackground";
        case NFluentColorKey::SystemFillColorCaution:
            return "SystemFillColorCaution";
        case NFluentColorKey::SystemFillColorCautionBackground:
            return "SystemFillColorCautionBackground";
        case NFluentColorKey::SystemFillColorCritical:
            return "SystemFillColorCritical";
        case NFluentColorKey::SystemFillColorCriticalBackground:
            return "SystemFillColorCriticalBackground";
        case NFluentColorKey::SystemFillColorNeutral:
            return "SystemFillColorNeutral";
        case NFluentColorKey::SystemFillColorNeutralBackground:
            return "SystemFillColorNeutralBackground";
        case NFluentColorKey::SystemFillColorSolidAttentionBackground:
            return "SystemFillColorSolidAttentionBackground";
        case NFluentColorKey::SystemFillColorSolidNeutral:
            return "SystemFillColorSolidNeutral";
        case NFluentColorKey::SystemFillColorSolidNeutralBackground:
            return "SystemFillColorSolidNeutralBackground";
        case NFluentColorKey::SystemFillColorSuccess:
            return "SystemFillColorSuccess";
        case NFluentColorKey::SystemFillColorSuccessBackground:
            return "SystemFillColorSuccessBackground";
        case NFluentColorKey::TextFillColorDisabled:
            return "TextFillColorDisabled";
        case NFluentColorKey::TextFillColorInverse:
            return "TextFillColorInverse";
        case NFluentColorKey::TextFillColorPrimary:
            return "TextFillColorPrimary";
        case NFluentColorKey::TextFillColorSecondary:
            return "TextFillColorSecondary";
        case NFluentColorKey::TextFillColorTertiary:
            return "TextFillColorTertiary";
        case NFluentColorKey::TextOnAccentFillColorDisabled:
            return "TextOnAccentFillColorDisabled";
        case NFluentColorKey::TextOnAccentFillColorPrimary:
            return "TextOnAccentFillColorPrimary";
        case NFluentColorKey::TextOnAccentFillColorSecondary:
            return "TextOnAccentFillColorSecondary";
        case NFluentColorKey::TextOnAccentFillColorSelectedText:
            return "TextOnAccentFillColorSelectedText";
        case NFluentColorKey::Count:
            return "";
    }
    return "";
}

// 字符串到枚举的转换函数
inline NFluentColorKey::Key stringToFluentColorKey(const QString& keyString) {
    if (keyString == "AccentFillColorDisabled") return NFluentColorKey::AccentFillColorDisabled;
    if (keyString == "AccentTextFillColorDisabled") return NFluentColorKey::AccentTextFillColorDisabled;
    if (keyString == "CardBackgroundFillColorDefault") return NFluentColorKey::CardBackgroundFillColorDefault;
    if (keyString == "CardBackgroundFillColorSecondary") return NFluentColorKey::CardBackgroundFillColorSecondary;
    if (keyString == "CardStrokeColorDefault") return NFluentColorKey::CardStrokeColorDefault;
    if (keyString == "CardStrokeColorDefaultSolid") return NFluentColorKey::CardStrokeColorDefaultSolid;
    if (keyString == "ControlAltFillColorDisabled") return NFluentColorKey::ControlAltFillColorDisabled;
    if (keyString == "ControlAltFillColorQuarternary") return NFluentColorKey::ControlAltFillColorQuarternary;
    if (keyString == "ControlAltFillColorSecondary") return NFluentColorKey::ControlAltFillColorSecondary;
    if (keyString == "ControlAltFillColorTertiary") return NFluentColorKey::ControlAltFillColorTertiary;
    if (keyString == "ControlAltFillColorTransparent") return NFluentColorKey::ControlAltFillColorTransparent;
    if (keyString == "ControlBaseLine") return NFluentColorKey::ControlBaseLine;
    if (keyString == "ControlFillColorDefault") return NFluentColorKey::ControlFillColorDefault;
    if (keyString == "ControlFillColorDisabled") return NFluentColorKey::ControlFillColorDisabled;
    if (keyString == "ControlFillColorInputActive") return NFluentColorKey::ControlFillColorInputActive;
    if (keyString == "ControlFillColorSecondary") return NFluentColorKey::ControlFillColorSecondary;
    if (keyString == "ControlFillColorTertiary") return NFluentColorKey::ControlFillColorTertiary;
    if (keyString == "ControlFillColorTransparent") return NFluentColorKey::ControlFillColorTransparent;
    if (keyString == "ControlOnImageFillColorDefault") return NFluentColorKey::ControlOnImageFillColorDefault;
    if (keyString == "ControlOnImageFillColorDisabled") return NFluentColorKey::ControlOnImageFillColorDisabled;
    if (keyString == "ControlOnImageFillColorSecondary") return NFluentColorKey::ControlOnImageFillColorSecondary;
    if (keyString == "ControlOnImageFillColorTertiary") return NFluentColorKey::ControlOnImageFillColorTertiary;
    if (keyString == "ControlSolidFillColorDefault") return NFluentColorKey::ControlSolidFillColorDefault;
    if (keyString == "ControlStrokeColorDefault") return NFluentColorKey::ControlStrokeColorDefault;
    if (keyString == "ControlStrokeColorForStrongFillWhenOnImage") return NFluentColorKey::ControlStrokeColorForStrongFillWhenOnImage;
    if (keyString == "ControlStrokeColorOnAccentDefault") return NFluentColorKey::ControlStrokeColorOnAccentDefault;
    if (keyString == "ControlStrokeColorOnAccentDisabled") return NFluentColorKey::ControlStrokeColorOnAccentDisabled;
    if (keyString == "ControlStrokeColorOnAccentSecondary") return NFluentColorKey::ControlStrokeColorOnAccentSecondary;
    if (keyString == "ControlStrokeColorOnAccentTertiary") return NFluentColorKey::ControlStrokeColorOnAccentTertiary;
    if (keyString == "ControlStrokeColorSecondary") return NFluentColorKey::ControlStrokeColorSecondary;
    if (keyString == "ControlStrongFillColorDefault") return NFluentColorKey::ControlStrongFillColorDefault;
    if (keyString == "ControlStrongFillColorDisabled") return NFluentColorKey::ControlStrongFillColorDisabled;
    if (keyString == "ControlStrongStrokeColorDefault") return NFluentColorKey::ControlStrongStrokeColorDefault;
    if (keyString == "ControlStrongStrokeColorDisabled") return NFluentColorKey::ControlStrongStrokeColorDisabled;
    if (keyString == "DividerStrokeColorDefault") return NFluentColorKey::DividerStrokeColorDefault;
    if (keyString == "FocusStrokeColorInner") return NFluentColorKey::FocusStrokeColorInner;
    if (keyString == "FocusStrokeColorOuter") return NFluentColorKey::FocusStrokeColorOuter;
    if (keyString == "LayerFillColorAlt") return NFluentColorKey::LayerFillColorAlt;
    if (keyString == "LayerFillColorDefault") return NFluentColorKey::LayerFillColorDefault;
    if (keyString == "LayerOnAccentAcrylicFillColorDefault") return NFluentColorKey::LayerOnAccentAcrylicFillColorDefault;
    if (keyString == "LayerOnAcrylicFillColorDefault") return NFluentColorKey::LayerOnAcrylicFillColorDefault;
    if (keyString == "LayerOnMicaBaseAltFillColorDefault") return NFluentColorKey::LayerOnMicaBaseAltFillColorDefault;
    if (keyString == "LayerOnMicaBaseAltFillColorSecondary") return NFluentColorKey::LayerOnMicaBaseAltFillColorSecondary;
    if (keyString == "LayerOnMicaBaseAltFillColorTertiary") return NFluentColorKey::LayerOnMicaBaseAltFillColorTertiary;
    if (keyString == "LayerOnMicaBaseAltFillColorTransparent") return NFluentColorKey::LayerOnMicaBaseAltFillColorTransparent;
    if (keyString == "SmokeFillColorDefault") return NFluentColorKey::SmokeFillColorDefault;
    if (keyString == "SolidBackgroundFillColorBase") return NFluentColorKey::SolidBackgroundFillColorBase;
    if (keyString == "SolidBackgroundFillColorBaseAlt") return NFluentColorKey::SolidBackgroundFillColorBaseAlt;
    if (keyString == "SolidBackgroundFillColorQuarternary") return NFluentColorKey::SolidBackgroundFillColorQuarternary;
    if (keyString == "SolidBackgroundFillColorSecondary") return NFluentColorKey::SolidBackgroundFillColorSecondary;
    if (keyString == "SolidBackgroundFillColorTertiary") return NFluentColorKey::SolidBackgroundFillColorTertiary;
    if (keyString == "SolidBackgroundFillColorTransparent") return NFluentColorKey::SolidBackgroundFillColorTransparent;
    if (keyString == "SubtleFillColorDisabled") return NFluentColorKey::SubtleFillColorDisabled;
    if (keyString == "SubtleFillColorSecondary") return NFluentColorKey::SubtleFillColorSecondary;
    if (keyString == "SubtleFillColorTertiary") return NFluentColorKey::SubtleFillColorTertiary;
    if (keyString == "SubtleFillColorTransparent") return NFluentColorKey::SubtleFillColorTransparent;
    if (keyString == "SurfaceStrokeColorDefault") return NFluentColorKey::SurfaceStrokeColorDefault;
    if (keyString == "SurfaceStrokeColorFlyout") return NFluentColorKey::SurfaceStrokeColorFlyout;
    if (keyString == "SurfaceStrokeColorInverse") return NFluentColorKey::SurfaceStrokeColorInverse;
    if (keyString == "SystemColorButtonFaceColor") return NFluentColorKey::SystemColorButtonFaceColor;
    if (keyString == "SystemColorButtonTextColor") return NFluentColorKey::SystemColorButtonTextColor;
    if (keyString == "SystemColorGrayTextColor") return NFluentColorKey::SystemColorGrayTextColor;
    if (keyString == "SystemColorHighlightColor") return NFluentColorKey::SystemColorHighlightColor;
    if (keyString == "SystemColorHighlightTextColor") return NFluentColorKey::SystemColorHighlightTextColor;
    if (keyString == "SystemColorHotlightColor") return NFluentColorKey::SystemColorHotlightColor;
    if (keyString == "SystemColorWindowColor") return NFluentColorKey::SystemColorWindowColor;
    if (keyString == "SystemColorWindowTextColor") return NFluentColorKey::SystemColorWindowTextColor;
    if (keyString == "SystemFillColorAttentionBackground") return NFluentColorKey::SystemFillColorAttentionBackground;
    if (keyString == "SystemFillColorCaution") return NFluentColorKey::SystemFillColorCaution;
    if (keyString == "SystemFillColorCautionBackground") return NFluentColorKey::SystemFillColorCautionBackground;
    if (keyString == "SystemFillColorCritical") return NFluentColorKey::SystemFillColorCritical;
    if (keyString == "SystemFillColorCriticalBackground") return NFluentColorKey::SystemFillColorCriticalBackground;
    if (keyString == "SystemFillColorNeutral") return NFluentColorKey::SystemFillColorNeutral;
    if (keyString == "SystemFillColorNeutralBackground") return NFluentColorKey::SystemFillColorNeutralBackground;
    if (keyString == "SystemFillColorSolidAttentionBackground") return NFluentColorKey::SystemFillColorSolidAttentionBackground;
    if (keyString == "SystemFillColorSolidNeutral") return NFluentColorKey::SystemFillColorSolidNeutral;
    if (keyString == "SystemFillColorSolidNeutralBackground") return NFluentColorKey::SystemFillColorSolidNeutralBackground;
    if (keyString == "SystemFillColorSuccess") return NFluentColorKey::SystemFillColorSuccess;
    if (keyString == "SystemFillColorSuccessBackground") return NFluentColorKey::SystemFillColorSuccessBackground;
    if (keyString == "TextFillColorDisabled") return NFluentColorKey::TextFillColorDisabled;
    if (keyString == "TextFillColorInverse") return NFluentColorKey::TextFillColorInverse;
    if (keyString == "TextFillColorPrimary") return NFluentColorKey::TextFillColorPrimary;
    if (keyString == "TextFillColorSecondary") return NFluentColorKey::TextFillColorSecondary;
    if (keyString == "TextFillColorTertiary") return NFluentColorKey::TextFillColorTertiary;
    if (keyString == "TextOnAccentFillColorDisabled") return NFluentColorKey::TextOnAccentFillColorDisabled;
    if (keyString == "TextOnAccentFillColorPrimary") return NFluentColorKey::TextOnAccentFillColorPrimary;
    if (keyString == "TextOnAccentFillColorSecondary") return NFluentColorKey::TextOnAccentFillColorSecondary;
    if (keyString == "TextOnAccentFillColorSelectedText") return NFluentColorKey::TextOnAccentFillColorSelectedText;
    return NFluentColorKey::Count; // 无效的键
}

// 暗色主题颜色
static const QMap<NFluentColorKey::Key, QColor> DarkThemeColors = {
    {NFluentColorKey::TextFillColorPrimary, QColor(255, 255, 255)},
    {NFluentColorKey::TextFillColorSecondary, QColor(255, 255, 255, 197)},
    {NFluentColorKey::TextFillColorTertiary, QColor(255, 255, 255, 135)},
    {NFluentColorKey::TextFillColorDisabled, QColor(255, 255, 255, 93)},
    {NFluentColorKey::TextFillColorInverse, QColor(0, 0, 0, 228)},
    {NFluentColorKey::AccentTextFillColorDisabled, QColor(255, 255, 255, 93)},
    {NFluentColorKey::TextOnAccentFillColorSelectedText, QColor(255, 255, 255)},
    {NFluentColorKey::TextOnAccentFillColorPrimary, QColor(0, 0, 0)},
    {NFluentColorKey::TextOnAccentFillColorSecondary, QColor(0, 0, 0, 128)},
    {NFluentColorKey::TextOnAccentFillColorDisabled, QColor(255, 255, 255, 135)},
    {NFluentColorKey::ControlFillColorDefault, QColor(255, 255, 255, 15)},
    {NFluentColorKey::ControlFillColorSecondary, QColor(255, 255, 255, 21)},
    {NFluentColorKey::ControlFillColorTertiary, QColor(255, 255, 255, 8)},
    {NFluentColorKey::ControlFillColorDisabled, QColor(255, 255, 255, 11)},
    {NFluentColorKey::ControlFillColorTransparent, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlFillColorInputActive, QColor(30, 30, 30, 179)},
    {NFluentColorKey::ControlStrongFillColorDefault, QColor(255, 255, 255, 139)},
    {NFluentColorKey::ControlStrongFillColorDisabled, QColor(255, 255, 255, 63)},
    {NFluentColorKey::ControlSolidFillColorDefault, QColor(69, 69, 69)},
    {NFluentColorKey::SubtleFillColorTransparent, QColor(255, 255, 255, 0)},
    {NFluentColorKey::SubtleFillColorSecondary, QColor(255, 255, 255, 15)},
    {NFluentColorKey::SubtleFillColorTertiary, QColor(255, 255, 255, 10)},
    {NFluentColorKey::SubtleFillColorDisabled, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlAltFillColorTransparent, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlAltFillColorSecondary, QColor(0, 0, 0, 25)},
    {NFluentColorKey::ControlAltFillColorTertiary, QColor(255, 255, 255, 11)},
    {NFluentColorKey::ControlAltFillColorQuarternary, QColor(255, 255, 255, 18)},
    {NFluentColorKey::ControlAltFillColorDisabled, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlOnImageFillColorDefault, QColor(28, 28, 28, 179)},
    {NFluentColorKey::ControlOnImageFillColorSecondary, QColor(26, 26, 26)},
    {NFluentColorKey::ControlOnImageFillColorTertiary, QColor(19, 19, 19)},
    {NFluentColorKey::ControlOnImageFillColorDisabled, QColor(30, 30, 30)},
    {NFluentColorKey::AccentFillColorDisabled, QColor(255, 255, 255, 40)},
    {NFluentColorKey::ControlStrokeColorDefault, QColor(255, 255, 255, 18)},
    {NFluentColorKey::ControlStrokeColorSecondary, QColor(255, 255, 255, 24)},
    {NFluentColorKey::ControlStrokeColorOnAccentDefault, QColor(255, 255, 255, 20)},
    {NFluentColorKey::ControlStrokeColorOnAccentSecondary, QColor(0, 0, 0, 35)},
    {NFluentColorKey::ControlStrokeColorOnAccentTertiary, QColor(0, 0, 0, 55)},
    {NFluentColorKey::ControlStrokeColorOnAccentDisabled, QColor(0, 0, 0, 51)},
    {NFluentColorKey::ControlStrokeColorForStrongFillWhenOnImage, QColor(0, 0, 0, 107)},
    {NFluentColorKey::CardStrokeColorDefault, QColor(0, 0, 0, 25)},
    {NFluentColorKey::CardStrokeColorDefaultSolid, QColor(28, 28, 28)},
    {NFluentColorKey::ControlStrongStrokeColorDefault, QColor(255, 255, 255, 139)},
    {NFluentColorKey::ControlStrongStrokeColorDisabled, QColor(255, 255, 255, 40)},
    {NFluentColorKey::SurfaceStrokeColorDefault, QColor(117, 117, 117, 102)},
    {NFluentColorKey::SurfaceStrokeColorFlyout, QColor(0, 0, 0, 51)},
    {NFluentColorKey::SurfaceStrokeColorInverse, QColor(0, 0, 0, 15)},
    {NFluentColorKey::DividerStrokeColorDefault, QColor(255, 255, 255, 21)},
    {NFluentColorKey::FocusStrokeColorOuter, QColor(255, 255, 255)},
    {NFluentColorKey::FocusStrokeColorInner, QColor(0, 0, 0, 179)},
    {NFluentColorKey::CardBackgroundFillColorDefault, QColor(255, 255, 255, 13)},
    {NFluentColorKey::CardBackgroundFillColorSecondary, QColor(255, 255, 255, 8)},
    {NFluentColorKey::SmokeFillColorDefault, QColor(0, 0, 0, 77)},
    {NFluentColorKey::LayerFillColorDefault, QColor(58, 58, 58, 76)},
    {NFluentColorKey::LayerFillColorAlt, QColor(255, 255, 255, 13)},
    {NFluentColorKey::LayerOnAcrylicFillColorDefault, QColor(255, 255, 255, 9)},
    {NFluentColorKey::LayerOnAccentAcrylicFillColorDefault, QColor(255, 255, 255, 9)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorDefault, QColor(58, 58, 58, 115)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorSecondary, QColor(255, 255, 255, 15)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorTertiary, QColor(44, 44, 44)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorTransparent, QColor(255, 255, 255, 0)},
    {NFluentColorKey::SolidBackgroundFillColorBase, QColor(32, 32, 32)},
    {NFluentColorKey::SolidBackgroundFillColorSecondary, QColor(28, 28, 28)},
    {NFluentColorKey::SolidBackgroundFillColorTertiary, QColor(40, 40, 40)},
    {NFluentColorKey::SolidBackgroundFillColorQuarternary, QColor(44, 44, 44)},
    {NFluentColorKey::SolidBackgroundFillColorTransparent, QColor(32, 32, 32, 0)},
    {NFluentColorKey::SolidBackgroundFillColorBaseAlt, QColor(10, 10, 10)},
    {NFluentColorKey::SystemFillColorSuccess, QColor(108, 203, 95)},
    {NFluentColorKey::SystemFillColorCaution, QColor(252, 225, 0)},
    {NFluentColorKey::SystemFillColorCritical, QColor(255, 153, 164)},
    {NFluentColorKey::SystemFillColorNeutral, QColor(255, 255, 255, 139)},
    {NFluentColorKey::SystemFillColorSolidNeutral, QColor(157, 157, 157)},
    {NFluentColorKey::SystemFillColorAttentionBackground, QColor(255, 255, 255, 8)},
    {NFluentColorKey::SystemFillColorSuccessBackground, QColor(57, 61, 27)},
    {NFluentColorKey::SystemFillColorCautionBackground, QColor(67, 53, 25)},
    {NFluentColorKey::SystemFillColorCriticalBackground, QColor(68, 39, 38)},
    {NFluentColorKey::SystemFillColorNeutralBackground, QColor(255, 255, 255, 8)},
    {NFluentColorKey::SystemFillColorSolidAttentionBackground, QColor(46, 46, 46)},
    {NFluentColorKey::SystemFillColorSolidNeutralBackground, QColor(46, 46, 46)},
    {NFluentColorKey::SystemColorWindowTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorWindowColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorButtonFaceColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorButtonTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorHighlightColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorHighlightTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorHotlightColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorGrayTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::ControlBaseLine, QColor(44, 44, 44)},
};

// 亮色主题颜色
static const QMap<NFluentColorKey::Key, QColor> LightThemeColors = {
    {NFluentColorKey::TextFillColorPrimary, QColor(0, 0, 0, 228)},
    {NFluentColorKey::TextFillColorSecondary, QColor(0, 0, 0, 158)},
    {NFluentColorKey::TextFillColorTertiary, QColor(0, 0, 0, 114)},
    {NFluentColorKey::TextFillColorDisabled, QColor(0, 0, 0, 92)},
    {NFluentColorKey::TextFillColorInverse, QColor(255, 255, 255)},
    {NFluentColorKey::AccentTextFillColorDisabled, QColor(0, 0, 0, 92)},
    {NFluentColorKey::TextOnAccentFillColorSelectedText, QColor(255, 255, 255)},
    {NFluentColorKey::TextOnAccentFillColorPrimary, QColor(255, 255, 255)},
    {NFluentColorKey::TextOnAccentFillColorSecondary, QColor(255, 255, 255, 179)},
    {NFluentColorKey::TextOnAccentFillColorDisabled, QColor(255, 255, 255)},
    {NFluentColorKey::ControlFillColorDefault, QColor(255, 255, 255, 179)},
    {NFluentColorKey::ControlFillColorSecondary, QColor(249, 249, 249, 128)},
    {NFluentColorKey::ControlFillColorTertiary, QColor(249, 249, 249, 77)},
    {NFluentColorKey::ControlFillColorDisabled, QColor(249, 249, 249, 77)},
    {NFluentColorKey::ControlFillColorTransparent, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlFillColorInputActive, QColor(255, 255, 255)},
    {NFluentColorKey::ControlStrongFillColorDefault, QColor(0, 0, 0, 114)},
    {NFluentColorKey::ControlStrongFillColorDisabled, QColor(0, 0, 0, 81)},
    {NFluentColorKey::ControlSolidFillColorDefault, QColor(255, 255, 255)},
    {NFluentColorKey::SubtleFillColorTransparent, QColor(255, 255, 255, 0)},
    {NFluentColorKey::SubtleFillColorSecondary, QColor(0, 0, 0, 9)},
    {NFluentColorKey::SubtleFillColorTertiary, QColor(0, 0, 0, 6)},
    {NFluentColorKey::SubtleFillColorDisabled, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlAltFillColorTransparent, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlAltFillColorSecondary, QColor(0, 0, 0, 6)},
    {NFluentColorKey::ControlAltFillColorTertiary, QColor(0, 0, 0, 15)},
    {NFluentColorKey::ControlAltFillColorQuarternary, QColor(0, 0, 0, 24)},
    {NFluentColorKey::ControlAltFillColorDisabled, QColor(255, 255, 255, 0)},
    {NFluentColorKey::ControlOnImageFillColorDefault, QColor(255, 255, 255, 201)},
    {NFluentColorKey::ControlOnImageFillColorSecondary, QColor(243, 243, 243)},
    {NFluentColorKey::ControlOnImageFillColorTertiary, QColor(235, 235, 235)},
    {NFluentColorKey::ControlOnImageFillColorDisabled, QColor(255, 255, 255, 0)},
    {NFluentColorKey::AccentFillColorDisabled, QColor(0, 0, 0, 55)},
    {NFluentColorKey::ControlStrokeColorDefault, QColor(0, 0, 0, 15)},
    {NFluentColorKey::ControlStrokeColorSecondary, QColor(0, 0, 0, 41)},
    {NFluentColorKey::ControlStrokeColorOnAccentDefault, QColor(255, 255, 255, 20)},
    {NFluentColorKey::ControlStrokeColorOnAccentSecondary, QColor(0, 0, 0, 102)},
    {NFluentColorKey::ControlStrokeColorOnAccentTertiary, QColor(0, 0, 0, 55)},
    {NFluentColorKey::ControlStrokeColorOnAccentDisabled, QColor(0, 0, 0, 15)},
    {NFluentColorKey::ControlStrokeColorForStrongFillWhenOnImage, QColor(255, 255, 255, 89)},
    {NFluentColorKey::CardStrokeColorDefault, QColor(0, 0, 0, 15)},
    {NFluentColorKey::CardStrokeColorDefaultSolid, QColor(235, 235, 235)},
    {NFluentColorKey::ControlStrongStrokeColorDefault, QColor(0, 0, 0, 114)},
    {NFluentColorKey::ControlStrongStrokeColorDisabled, QColor(0, 0, 0, 55)},
    {NFluentColorKey::SurfaceStrokeColorDefault, QColor(117, 117, 117, 102)},
    {NFluentColorKey::SurfaceStrokeColorFlyout, QColor(0, 0, 0, 15)},
    {NFluentColorKey::SurfaceStrokeColorInverse, QColor(255, 255, 255, 21)},
    {NFluentColorKey::DividerStrokeColorDefault, QColor(0, 0, 0, 15)},
    {NFluentColorKey::FocusStrokeColorOuter, QColor(0, 0, 0, 228)},
    {NFluentColorKey::FocusStrokeColorInner, QColor(255, 255, 255, 179)},
    {NFluentColorKey::CardBackgroundFillColorDefault, QColor(255, 255, 255, 179)},
    {NFluentColorKey::CardBackgroundFillColorSecondary, QColor(246, 246, 246, 128)},
    {NFluentColorKey::SmokeFillColorDefault, QColor(0, 0, 0, 77)},
    {NFluentColorKey::LayerFillColorDefault, QColor(255, 255, 255, 128)},
    {NFluentColorKey::LayerFillColorAlt, QColor(255, 255, 255)},
    {NFluentColorKey::LayerOnAcrylicFillColorDefault, QColor(255, 255, 255, 64)},
    {NFluentColorKey::LayerOnAccentAcrylicFillColorDefault, QColor(255, 255, 255, 64)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorDefault, QColor(255, 255, 255, 179)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorSecondary, QColor(0, 0, 0, 10)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorTertiary, QColor(249, 249, 249)},
    {NFluentColorKey::LayerOnMicaBaseAltFillColorTransparent, QColor(0, 0, 0, 0)},
    {NFluentColorKey::SolidBackgroundFillColorBase, QColor(243, 243, 243)},
    {NFluentColorKey::SolidBackgroundFillColorSecondary, QColor(238, 238, 238)},
    {NFluentColorKey::SolidBackgroundFillColorTertiary, QColor(249, 249, 249)},
    {NFluentColorKey::SolidBackgroundFillColorQuarternary, QColor(255, 255, 255)},
    {NFluentColorKey::SolidBackgroundFillColorTransparent, QColor(243, 243, 243, 0)},
    {NFluentColorKey::SolidBackgroundFillColorBaseAlt, QColor(218, 218, 218)},
    {NFluentColorKey::SystemFillColorSuccess, QColor(15, 123, 15)},
    {NFluentColorKey::SystemFillColorCaution, QColor(157, 93, 0)},
    {NFluentColorKey::SystemFillColorCritical, QColor(196, 43, 28)},
    {NFluentColorKey::SystemFillColorNeutral, QColor(0, 0, 0, 114)},
    {NFluentColorKey::SystemFillColorSolidNeutral, QColor(138, 138, 138)},
    {NFluentColorKey::SystemFillColorAttentionBackground, QColor(246, 246, 246, 128)},
    {NFluentColorKey::SystemFillColorSuccessBackground, QColor(223, 246, 221)},
    {NFluentColorKey::SystemFillColorCautionBackground, QColor(255, 244, 206)},
    {NFluentColorKey::SystemFillColorCriticalBackground, QColor(253, 231, 233)},
    {NFluentColorKey::SystemFillColorNeutralBackground, QColor(0, 0, 0, 6)},
    {NFluentColorKey::SystemFillColorSolidAttentionBackground, QColor(247, 247, 247)},
    {NFluentColorKey::SystemFillColorSolidNeutralBackground, QColor(243, 243, 243)},
    {NFluentColorKey::SystemColorWindowTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorWindowColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorButtonFaceColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorButtonTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorHighlightColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorHighlightTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorHotlightColor, QColor(255, 0, 255)},
    {NFluentColorKey::SystemColorGrayTextColor, QColor(255, 0, 255)},
    {NFluentColorKey::ControlBaseLine, QColor(209, 209, 209)},
};

#endif // NFLUENTCOLORS_H
