#!/usr/bin/env python3
import os
import re
from pathlib import Path


def parse_css_file(css_path):
    """解析本地 CSS 文件内容，提取图标名称和 Unicode"""
    if not os.path.exists(css_path):
        print(f"Error: CSS file not found: {css_path}")
        return []

    with open(css_path, 'r', encoding='utf-8') as f:
        css_content = f.read()

    pattern = r'\.icon-ic_fluent_([a-zA-Z0-9_]+):before\s*{\s*content:\s*"\\([a-fA-F0-9]+)";'
    matches = re.findall(pattern, css_content)

    icons = []
    for match in matches:
        words = match[0].split('_')
        name = ''.join(word.capitalize() for word in words)
        unicode_value = match[1]
        icons.append((name, unicode_value))

    return sorted(icons, key=lambda x: x[0])


def generate_enum_header(regular_icons, filled_icons):
    """生成包含两个枚举的头文件内容"""
    header = """// WARNING: This file is automatically generated.
// DO NOT EDIT IT MANUALLY!
//
// Generated from Microsoft's Fluent System Icons
// Source: https://github.com/microsoft/fluentui-system-icons
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#ifndef QTNATIVEUI_NICONENUMS_H
#define QTNATIVEUI_NICONENUMS_H

#include <QMetaEnum>
#include "stdafx.h"

#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0)
#define Q_BEGIN_ENUM_CREATE(CLASS)                                                                                     \\
    namespace CLASS {                                                                                                  \\
    Q_NAMESPACE_EXPORT(QTNATIVEUI_EXPORT)

#define Q_END_ENUM_CREATE(CLASS) }

#define Q_ENUM_CREATE(CLASS) Q_ENUM_NS(CLASS)
#else
#define Q_BEGIN_ENUM_CREATE(CLASS)                                                                                     \\
    class QTNATIVEUI_EXPORT CLASS : public QObject {                                                                   \\
        Q_OBJECT                                                                                                       \\
      public:

#define Q_END_ENUM_CREATE(CLASS)                                                                                       \\
  private:                                                                                                             \\
    Q_DISABLE_COPY(CLASS)                                                                                              \\
    }                                                                                                                  \\
    ;

#define Q_ENUM_CREATE(CLASS) Q_ENUM(CLASS)
#endif

// Regular Icons
Q_BEGIN_ENUM_CREATE(NRegularIconType)
enum Icon {
    None = 0x0000,
"""
    # 添加 Regular 图标
    for name, unicode in regular_icons:
        header += f"    {name} = 0x{unicode},\n"

    header += """};
Q_ENUM_CREATE(Icon)
Q_END_ENUM_CREATE(NRegularIconType)

// Filled Icons
Q_BEGIN_ENUM_CREATE(NFilledIconType)
enum Icon {
    None = 0x0000,
"""
    # 添加 Filled 图标
    for name, unicode in filled_icons:
        header += f"    {name} = 0x{unicode},\n"

    header += """};
Q_ENUM_CREATE(Icon)
Q_END_ENUM_CREATE(NFilledIconType)

#endif // QTNATIVEUI_NICONENUMS_H
"""
    return header


def main():
    tools_dir = Path(__file__).parent
    resources_dir = tools_dir / "resources"

    regular_css = resources_dir / "FluentSystemIcons-Regular.css"
    filled_css = resources_dir / "FluentSystemIcons-Filled.css"

    regular_icons = []
    filled_icons = []

    if regular_css.exists():
        regular_icons = parse_css_file(regular_css)
        print(f"Regular icons: {len(regular_icons)}")

    if filled_css.exists():
        filled_icons = parse_css_file(filled_css)
        print(f"Filled icons: {len(filled_icons)}")

    if not regular_icons and not filled_icons:
        print("Error: No icons found in CSS files")
        return

    output_dir = Path("../include/QtNativeUI")
    output_dir.mkdir(parents=True, exist_ok=True)

    header_content = generate_enum_header(regular_icons, filled_icons)

    output_file = output_dir / "NIconEnums.h"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header_content)

    print(f"Generated {output_file}")
    print(f"Total icons: {len(regular_icons) + len(filled_icons)}")


if __name__ == "__main__":
    main()
